language: php

dist: trusty

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit 

after_script:
  - php vendor/bin/coveralls -v
